### ISSUE TITLE
Running on the server without X

### ISSUE THREAD

**Issue by masscream** [yaqwsx/utility#5]
Hello, not sure if this is really an issue or the script just was not intended for servers without X. However I'm trying to run it there. On the server there is no X, therefore this may be causing the issue that the script can't properly display or / and read the captcha. Could there be a way to solve this, please ? The captcha can be read or displayed in ascii art, if not possible to catch it automatically, then allow the manual input or so. Thank you for consideration.

Caching 30 captchas, please wait
Traceback (most recent call last):
  File "vzum", line 184, in <module>
    name, url = file_download_info(session, args.url, "Getting info")
  File "vzum", line 74, in file_download_info
    c_value = solve_captcha_user(c_img, user_message)
  File "vzum", line 40, in solve_captcha_user
    root = tk.Tk()
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by yaqwsx** [comment]
So far, I have no plans to support headless running. I can't imagine how would you show CAPTCHa as ASCII art. Also, I have no tools to solve captchas automatically and I am against supporting services like DeathByCaptcha.com.

However, feel free to fork your own version of vzum.

**Comment by masscream** [comment]
Back in the time, I was using this
https://github.com/mcrapet/plowshare-modules-legacy/blob/master/uloz_to.sh

It was able to convert the captcha into the plain ascii art, however it did not support threaded downloads which is the key feature. Even though it was displayed strange way, it could have been used.

I found a temporary fix in this article
https://askubuntu.com/questions/203173/run-application-on-local-machine-and-show-gui-on-remote-display
so I can shoot the X windows to the client side, however the X  / captcha independence one day would be still great.

**Comment by yaqwsx** [comment]
The script you posted uses something called `captcha_process` which I struggle to find.

**Comment by yaqwsx** [comment]
There is no activity for nearly two months, closing - feel free to reopen if you come up with a feasible solution.
